### DISCUSSION TITLE
ArchR conda

### DISCUSSION THREAD

**Discussion by simoriva** [GreenleafLab/ArchR#1553] [General]
Hi @rcorces, 

I saw an old (2021) discussion about snakemake and conda, but during this time, something maybe changed.

So, I was wondering, recently, did you plan to upload ArchR on Anaconda?

Best, 
Simone

**Comment by rcorces** [comment]
This is not in our plans but if someone wants to put together a bioconda recipe, I'm happy to look at it

**Comment by simoriva** [comment]
It took a bit of time to test it, but I finally have a functional conda recipe:
```
{% set version = '1.0.2' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-archr
  version: {{ version|replace("-", "_") }}

source:

  git_url: git@github.com:GreenleafLab/ArchR
  git_tag: v1.0.2

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0
  # no skip

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}git
    - {{ posix }}zip               # [win]

  host:
    - r-base >=4.1.1
    - bioconductor-biocgenerics
    - bioconductor-biostrings
    - bioconductor-complexheatmap
    - bioconductor-genomicranges
    - bioconductor-go.db #=3.13
    - r-matrix
    - r-rcpp >=0.12.16
    - bioconductor-rsamtools
    - bioconductor-s4vectors >=0.9.25
    - bioconductor-summarizedexperiment
    - bioconductor-chromvar
    - r-data.table
    - r-ggplot2
    - r-ggrepel
    - r-gridextra
    - r-gtable
    - r-gtools
    - r-magrittr
    - r-matrixstats
    - bioconductor-motifmatchr
    - r-nabor
    - r-plyr
    - bioconductor-rhdf5
    - r-stringr
    - r-uwot

  run:
    - r-base >=4.1.1
    - {{native}}gcc-libs         # [win]
    - bioconductor-biocgenerics
    - bioconductor-biostrings
    - bioconductor-complexheatmap
    - bioconductor-genomicranges
    - bioconductor-go.db #=3.13
    - r-matrix
    - r-rcpp >=0.12.16
    - bioconductor-rsamtools
    - bioconductor-s4vectors >=0.9.25
    - bioconductor-summarizedexperiment
    - bioconductor-chromvar
    - r-data.table
    - r-ggplot2
    - r-ggrepel
    - r-gridextra
    - r-gtable
    - r-gtools
    - r-magrittr
    - r-matrixstats
    - bioconductor-motifmatchr
    - r-nabor
    - r-plyr
    - bioconductor-rhdf5
    - r-stringr
    - r-uwot

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('ArchR')"           # [not win]
    - "\"%R%\" -e \"library('ArchR')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: git@github.com:GreenleafLab/ArchR
  license: GPL-2
  summary: This package is designed to streamline scATAC analyses in R.
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

# The original CRAN metadata for this package was:

# Package: ArchR
# Type: Package
# Date: 2022-04-03
# Title: Analyzing single-cell regulatory chromatin in R.
# Version: 1.0.2
# Authors@R: c( person("Jeffrey", "Granja", email = "jgranja.stanford@gmail.com", role = c("aut","cre")), person("Ryan", "Corces", role = "aut"))
# Description: This package is designed to streamline scATAC analyses in R.
# Roxygen: list(markdown = TRUE)
# License: GPL (>= 2)
# LinkingTo: Rcpp
# LazyData: TRUE
# RoxygenNote: 7.1.2
# Encoding: UTF-8
# Imports: ggplot2, SummarizedExperiment, data.table, Matrix, rhdf5, magrittr, S4Vectors (>= 0.9.25), BiocGenerics, Rcpp (>= 0.12.16), matrixStats, plyr, nabor, motifmatchr, chromVAR, uwot, ggrepel, Rsamtools, gtable, gtools, stringr, grid, gridExtra, Biostrings, ComplexHeatmap, GenomicRanges
# Depends:
# Collate: 'AllClasses.R' 'AnnotationGenome.R' 'AnnotationPeaks.R' 'ArchRBrowser.R' 'ArchRHeatmap.R' 'ArrowRead.R' 'ArrowUtils.R' 'ArrowWrite.R' 'BulkProjection.R' 'Clustering.R' 'ColorPalettes.R' 'CreateArrow.R' 'DoubletsScores.R' 'Embedding.R' 'FilterCells.R' 'Footprinting.R' 'GRangesUtils.R' 'GgplotUtils.R' 'GlobalDefaults.R' 'GroupCoverages.R' 'HelperUtils.R' 'GroupExport.R' 'Harmony.R' 'HiddenUtils.R' 'Imputation.R' 'InputData.R' 'IntegrativeAnalysis.R' 'IterativeLSI.R' 'LoggerUtils.R' 'MarkerFeatures.R' 'MatrixDeviations.R' 'MatrixFeatures.R' 'MatrixGeneExpression.R' 'MatrixGeneScores.R' 'MatrixTiles.R' 'ModuleScore.R' 'MultiModal.R' 'ProjectMethods.R' 'QualityControl.R' 'RNAIntegration.R' 'RcppExports.R' 'ReproduciblePeakSet.R' 'Trajectory.R' 'ValidationUtils.R' 'VisualizeData.R'

# See
# https://docs.conda.io/projects/conda-build for
# more information about meta.yaml

```

I would mention a couple of problems related to ArchR::installExtraPackages().

Unfortunately, I couldn't manage to integrate the extra packages, especially for the following packages:
- immunogenomics/harmony
- immunogenomics/presto
Reason: they are available only on GitHub.
On the other hand, inside the archR recipe can be easily integrated with the other (not aforementioned) extra packages.

I needed the conda version of archR because we are developing a pipeline for intersecting genetics and scATAC-seq data. 

Btw, I stored the conda version in my anaconda channel (here is the [link](https://anaconda.org/sgriva/r-archr)), and it is fully functional now.

What are your thoughts?

Best,
Simone
